//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Versagen.XML.Schemas {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="versagen")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="versagen", IsNullable=false)]
    public partial class resource {
        
        private System.Xml.XmlQualifiedName nameField;
        
        private description contentDescriptionField;
        
        private string locationField;
        
        /// <remarks/>
        public System.Xml.XmlQualifiedName name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public description contentDescription {
            get {
                return this.contentDescriptionField;
            }
            set {
                this.contentDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="versagen")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="versagen", IsNullable=false)]
    public partial class description {
        
        private descriptionSubstitution[] substitutionField;
        
        private resource resourceField;
        
        private string[] textField;
        
        private string conditionRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("substitution")]
        public descriptionSubstitution[] substitution {
            get {
                return this.substitutionField;
            }
            set {
                this.substitutionField = value;
            }
        }
        
        /// <remarks/>
        public resource resource {
            get {
                return this.resourceField;
            }
            set {
                this.resourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string conditionRef {
            get {
                return this.conditionRefField;
            }
            set {
                this.conditionRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="versagen")]
    public partial class descriptionSubstitution {
        
        private string subvalueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string subvalue {
            get {
                return this.subvalueField;
            }
            set {
                this.subvalueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="versagen")]
    public partial class stat {
        
        private System.Xml.XmlQualifiedName statNameField;
        
        private bool absoluteSetField;
        
        private int maxValueField;
        
        private int valueField;
        
        /// <remarks/>
        public System.Xml.XmlQualifiedName statName {
            get {
                return this.statNameField;
            }
            set {
                this.statNameField = value;
            }
        }
        
        /// <remarks/>
        public bool absoluteSet {
            get {
                return this.absoluteSetField;
            }
            set {
                this.absoluteSetField = value;
            }
        }
        
        /// <remarks/>
        public int maxValue {
            get {
                return this.maxValueField;
            }
            set {
                this.maxValueField = value;
            }
        }
        
        /// <remarks/>
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(booleanCondition))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="versagen")]
    public abstract partial class condition {
        
        private condition[] subConditionField;
        
        private string refNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subCondition")]
        public condition[] subCondition {
            get {
                return this.subConditionField;
            }
            set {
                this.subConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string refName {
            get {
                return this.refNameField;
            }
            set {
                this.refNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="versagen")]
    [System.Xml.Serialization.XmlRootAttribute("someCondition", Namespace="versagen", IsNullable=false)]
    public partial class booleanCondition : condition {
        
        private bool valueField;
        
        /// <remarks/>
        public bool value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="versagen")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="versagen", IsNullable=false)]
    public partial class statDef {
        
        private System.Xml.XmlQualifiedName nameField;
        
        private int capField;
        
        private statDefStatType statTypeField;
        
        private condition[] conditionField;
        
        private System.Xml.XmlQualifiedName conditionRefField;
        
        public statDef() {
            this.capField = 100;
            this.statTypeField = statDefStatType.@static;
        }
        
        /// <remarks/>
        public System.Xml.XmlQualifiedName name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int cap {
            get {
                return this.capField;
            }
            set {
                this.capField = value;
            }
        }
        
        /// <remarks/>
        public statDefStatType statType {
            get {
                return this.statTypeField;
            }
            set {
                this.statTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("condition")]
        public condition[] condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlQualifiedName conditionRef {
            get {
                return this.conditionRefField;
            }
            set {
                this.conditionRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="versagen")]
    public enum statDefStatType {
        
        /// <remarks/>
        @static,
        
        /// <remarks/>
        depletable,
        
        /// <remarks/>
        trueFalse,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="versagen")]
    [System.Xml.Serialization.XmlRootAttribute("DiceRoll", Namespace="versagen", IsNullable=false)]
    public partial class roll {
        
        private int numberDiceField;
        
        private int numberSidesField;
        
        private bool accumulateField;
        
        public roll() {
            this.accumulateField = true;
        }
        
        /// <remarks/>
        public int numberDice {
            get {
                return this.numberDiceField;
            }
            set {
                this.numberDiceField = value;
            }
        }
        
        /// <remarks/>
        public int numberSides {
            get {
                return this.numberSidesField;
            }
            set {
                this.numberSidesField = value;
            }
        }
        
        /// <remarks/>
        public bool accumulate {
            get {
                return this.accumulateField;
            }
            set {
                this.accumulateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="versagen")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="versagen", IsNullable=false)]
    public partial class effect {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("applyModifiersImmediately", typeof(bool))]
        [System.Xml.Serialization.XmlElementAttribute("attachCondition", typeof(condition))]
        [System.Xml.Serialization.XmlElementAttribute("description", typeof(description))]
        [System.Xml.Serialization.XmlElementAttribute("name", typeof(System.Xml.XmlQualifiedName))]
        [System.Xml.Serialization.XmlElementAttribute("refName", typeof(System.Xml.XmlQualifiedName))]
        [System.Xml.Serialization.XmlElementAttribute("releaseCondition", typeof(condition))]
        [System.Xml.Serialization.XmlElementAttribute("rollModifier", typeof(roll))]
        [System.Xml.Serialization.XmlElementAttribute("statMod", typeof(stat))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="versagen", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        applyModifiersImmediately,
        
        /// <remarks/>
        attachCondition,
        
        /// <remarks/>
        description,
        
        /// <remarks/>
        name,
        
        /// <remarks/>
        refName,
        
        /// <remarks/>
        releaseCondition,
        
        /// <remarks/>
        rollModifier,
        
        /// <remarks/>
        statMod,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="versagen")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="versagen", IsNullable=false)]
    public partial class action {
        
        private System.Xml.XmlQualifiedName nameField;
        
        private description descriptionField;
        
        private condition[] useConditionField;
        
        private effect[] targetEffectField;
        
        private effect[] selfEffectField;
        
        private roll hitChanceField;
        
        /// <remarks/>
        public System.Xml.XmlQualifiedName name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public description description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("useCondition")]
        public condition[] useCondition {
            get {
                return this.useConditionField;
            }
            set {
                this.useConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("targetEffect")]
        public effect[] targetEffect {
            get {
                return this.targetEffectField;
            }
            set {
                this.targetEffectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("selfEffect")]
        public effect[] selfEffect {
            get {
                return this.selfEffectField;
            }
            set {
                this.selfEffectField = value;
            }
        }
        
        /// <remarks/>
        public roll hitChance {
            get {
                return this.hitChanceField;
            }
            set {
                this.hitChanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="versagen")]
    [System.Xml.Serialization.XmlRootAttribute("WorthyInventory", Namespace="versagen", IsNullable=false)]
    public partial class inventory {
        
        private item[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item")]
        public item[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="versagen")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="versagen", IsNullable=false)]
    public partial class item {
        
        private object[] itemsField;
        
        private string typeNameField;
        
        private string specialNameField;
        
        private string typeRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("action", typeof(action))]
        [System.Xml.Serialization.XmlElementAttribute("description", typeof(description))]
        [System.Xml.Serialization.XmlElementAttribute("holdEffect", typeof(effect))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string TypeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string SpecialName {
            get {
                return this.specialNameField;
            }
            set {
                this.specialNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string TypeRef {
            get {
                return this.typeRefField;
            }
            set {
                this.typeRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="versagen")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="versagen", IsNullable=false)]
    public partial class entity {
        
        private string nameField;
        
        private description[] physicalDescriptionField;
        
        private description[] personalityField;
        
        private stat statField;
        
        private item[] inventoryField;
        
        private entityActionAndContext[] actionAndContextField;
        
        private System.Xml.XmlQualifiedName templateNameField;
        
        private System.Xml.XmlQualifiedName entityNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("physicalDescription")]
        public description[] physicalDescription {
            get {
                return this.physicalDescriptionField;
            }
            set {
                this.physicalDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("personality")]
        public description[] personality {
            get {
                return this.personalityField;
            }
            set {
                this.personalityField = value;
            }
        }
        
        /// <remarks/>
        public stat stat {
            get {
                return this.statField;
            }
            set {
                this.statField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public item[] inventory {
            get {
                return this.inventoryField;
            }
            set {
                this.inventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("actionAndContext")]
        public entityActionAndContext[] actionAndContext {
            get {
                return this.actionAndContextField;
            }
            set {
                this.actionAndContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName templateName {
            get {
                return this.templateNameField;
            }
            set {
                this.templateNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName entityName {
            get {
                return this.entityNameField;
            }
            set {
                this.entityNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="versagen")]
    public partial class entityActionAndContext {
        
        private action actionField;
        
        private condition conditionField;
        
        /// <remarks/>
        public action action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        public condition condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(locationDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(locationReference))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="versagen")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="versagen", IsNullable=false)]
    public abstract partial class location {
        
        private condition[] conditionField;
        
        private locationDescription[] descriptionField;
        
        private locationSublocation[] sublocationField;
        
        private item[] presentItemField;
        
        private entity[] entityField;
        
        private System.Xml.XmlElement extraDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("condition")]
        public condition[] condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("description")]
        public locationDescription[] description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sublocation")]
        public locationSublocation[] sublocation {
            get {
                return this.sublocationField;
            }
            set {
                this.sublocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("presentItem")]
        public item[] presentItem {
            get {
                return this.presentItemField;
            }
            set {
                this.presentItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entity")]
        public entity[] entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlElement extraData {
            get {
                return this.extraDataField;
            }
            set {
                this.extraDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="versagen")]
    public partial class locationDescription : description {
        
        private locationDescriptionDescritpionType descritpionTypeField;
        
        public locationDescription() {
            this.descritpionTypeField = locationDescriptionDescritpionType.append;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(locationDescriptionDescritpionType.append)]
        public locationDescriptionDescritpionType descritpionType {
            get {
                return this.descritpionTypeField;
            }
            set {
                this.descritpionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="versagen")]
    public enum locationDescriptionDescritpionType {
        
        /// <remarks/>
        append,
        
        /// <remarks/>
        replace,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="versagen")]
    public partial class locationSublocation : location {
        
        private string displayNameField;
        
        private string narrationNotesField;
        
        private string entryConditionField;
        
        private bool allowReturnToParentField;
        
        private bool allowReturnToParentFieldSpecified;
        
        /// <remarks/>
        public string displayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string narrationNotes {
            get {
                return this.narrationNotesField;
            }
            set {
                this.narrationNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string entryCondition {
            get {
                return this.entryConditionField;
            }
            set {
                this.entryConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool allowReturnToParent {
            get {
                return this.allowReturnToParentField;
            }
            set {
                this.allowReturnToParentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool allowReturnToParentSpecified {
            get {
                return this.allowReturnToParentFieldSpecified;
            }
            set {
                this.allowReturnToParentFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="versagen")]
    public partial class locationDefinition : location {
        
        private string displayNameField;
        
        private string narrationNotesField;
        
        private System.Xml.XmlQualifiedName nameField;
        
        /// <remarks/>
        public string displayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string narrationNotes {
            get {
                return this.narrationNotesField;
            }
            set {
                this.narrationNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="versagen")]
    public partial class locationReference : location {
        
        private string displayNameField;
        
        private string narrationNotesField;
        
        private string refFromLocaionField;
        
        private locationReferenceOverrideModeDefault overrideModeDefaultField;
        
        public locationReference() {
            this.overrideModeDefaultField = locationReferenceOverrideModeDefault.append;
        }
        
        /// <remarks/>
        public string displayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string narrationNotes {
            get {
                return this.narrationNotesField;
            }
            set {
                this.narrationNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string refFromLocaion {
            get {
                return this.refFromLocaionField;
            }
            set {
                this.refFromLocaionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(locationReferenceOverrideModeDefault.append)]
        public locationReferenceOverrideModeDefault overrideModeDefault {
            get {
                return this.overrideModeDefaultField;
            }
            set {
                this.overrideModeDefaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="versagen")]
    public enum locationReferenceOverrideModeDefault {
        
        /// <remarks/>
        replace,
        
        /// <remarks/>
        append,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="versagen")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="versagen", IsNullable=false)]
    public partial class refTo {
        
        private System.Xml.XmlElement anyField;
        
        private System.Xml.XmlQualifiedName categoryField;
        
        private string pathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="versagen")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="versagen", IsNullable=false)]
    public partial class Story {
        
        private string nameField;
        
        private description plotDescriptionField;
        
        private ushort[] itemsField;
        
        private ItemsChoiceType1[] itemsElementNameField;
        
        private ushort charsPerPlayerField;
        
        private bool charsPerPlayerFieldSpecified;
        
        private ushort maxInPartyField;
        
        private bool maxInPartyFieldSpecified;
        
        private condition[] clearConditionField;
        
        private object[] items1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public description plotDescription {
            get {
                return this.plotDescriptionField;
            }
            set {
                this.plotDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("maxPlayers", typeof(ushort))]
        [System.Xml.Serialization.XmlElementAttribute("minPlayers", typeof(ushort))]
        [System.Xml.Serialization.XmlElementAttribute("numberPlayers", typeof(ushort))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public ushort[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        public ushort charsPerPlayer {
            get {
                return this.charsPerPlayerField;
            }
            set {
                this.charsPerPlayerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool charsPerPlayerSpecified {
            get {
                return this.charsPerPlayerFieldSpecified;
            }
            set {
                this.charsPerPlayerFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ushort maxInParty {
            get {
                return this.maxInPartyField;
            }
            set {
                this.maxInPartyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxInPartySpecified {
            get {
                return this.maxInPartyFieldSpecified;
            }
            set {
                this.maxInPartyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("clearCondition")]
        public condition[] clearCondition {
            get {
                return this.clearConditionField;
            }
            set {
                this.clearConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("locationTree", typeof(location))]
        [System.Xml.Serialization.XmlElementAttribute("refTo", typeof(refTo))]
        public object[] Items1 {
            get {
                return this.items1Field;
            }
            set {
                this.items1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="versagen", IncludeInSchema=false)]
    public enum ItemsChoiceType1 {
        
        /// <remarks/>
        maxPlayers,
        
        /// <remarks/>
        minPlayers,
        
        /// <remarks/>
        numberPlayers,
    }
}
